sudo: false
language: node_js
node_js:
  - 10
  - 11
  - 12
cache: yarn
install:
  - yarn --ignore-engines
script:
  - npm run lint
  - npm run test
  - npm run build
after_script:
  - npm run bundlesize