name: test
on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: cache yarn.lock
        uses: actions/cache@v2
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: hack for singe file
        run: |
          if [ ! -d "package-temp-dir" ]; then
            mkdir package-temp-dir
          fi
          cp yarn.lock package-temp-dir

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/yarn.lock') }}

      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn

  setup-react-16:
    runs-on: ubuntu-latest
    env:
      REACT: 16
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install react 16
        run: lerna exec --scope zarm -- yarn install-react-16
    needs: setup

  compile-cli:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: restore cache from yarn.lock
        uses: actions/cache@v2
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/yarn.lock') }}

      - name: cache zarm-cli/lib
        uses: actions/cache@v2
        with:
          path: packages/zarm-cli/lib
          key: cli-lib-${{ github.sha }}

      - name: compile cli
        run: lerna exec --scope @zarm-design/cli -- yarn build
    needs: setup

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: compile zarm
        run: lerna exec --scope zarm -- yarn build:es && yarn build:lib
    needs: compile-cli

  compile-react-16:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: compile
        run: lerna exec --scope zarm -- yarn build:es && yarn build:lib
    needs: [setup-react-16, compile-cli]

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: restore cache from yarn.lock
        uses: actions/cache@v2
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/yarn.lock') }}

      - name: lint
        run: yarn lint
    needs: setup

  react-17:
    name: react@17.x
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          # codecov.io requires a fetch depth > 1.
          fetch-depth: 2

      - name: test
        run: lerna exec --scope zarm -- yarn coverage
      
      - name: coverage
        run: bash <(curl -s https://codecov.io/bash)
    needs: compile-cli

  react-17-dist:
    name: react@17.x / dist
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: dist
        run: lerna exec --scope zarm -- yarn build:umd
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: check
        run: lerna exec --scope zarm -- node ./tests/dekko/dist.test.js

      - name: bundlesize
        run: lerna exec --scope zarm -- yarn bundlesize
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
    needs: compile-cli

  react-16:
    name: react@16.x
    runs-on: ubuntu-latest
    env:
      REACT: 16
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install react 16
        run: lerna exec --scope zarm -- yarn install-react-16

      - name: test
        run: lerna exec --scope zarm -- yarn test
    needs: [setup-react-16, compile-cli]

  react-16-dist:
    name: react@16.x / dist
    runs-on: ubuntu-latest
    env:
      REACT: 16
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install react 16
        run: lerna exec --scope zarm -- yarn install-react-16

      - name: dist
        run: lerna exec --scope zarm -- yarn build:umd
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: check
        run: lerna exec --scope zarm -- node ./tests/dekko/dist.test.js

      - name: bundlesize
        run: lerna exec --scope zarm -- yarn bundlesize
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
    needs: [setup-react-16, compile-cli]
