name: test
on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: cache lerna
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

  setup-react-16:
    runs-on: ubuntu-latest
    env:
      REACT: 16
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install react 16
        run: lerna exec --scope zarm -- yarn install-react-16
    needs: setup

  compile-cli:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: cache cli
        uses: actions/cache@v2
        with:
          path: packages/zarm-cli/lib
          key: cli-${{ github.sha }}

      - name: compile cli
        run: lerna exec --scope @zarm-design/cli -- yarn build
    needs: setup

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: restore cli
        uses: actions/cache@v2
        with:
          path: packages/zarm-cli/lib
          key: cli-${{ github.sha }}

      - name: compile
        run: |
          lerna exec --scope zarm -- yarn build:es
          lerna exec --scope zarm -- yarn build:lib
    needs: compile-cli

  compile-react-16:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: restore cli
        uses: actions/cache@v2
        with:
          path: packages/zarm-cli/lib
          key: cli-${{ github.sha }}

      - name: compile
        run: |
          lerna exec --scope zarm -- yarn build:es
          lerna exec --scope zarm -- yarn build:lib
    needs: [setup-react-16, compile-cli]

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: lint
        run: yarn lint
    needs: setup

  react-17:
    name: react@17.x
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          # codecov.io requires a fetch depth > 1.
          fetch-depth: 2

      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: restore cli
        uses: actions/cache@v2
        with:
          path: packages/zarm-cli/lib
          key: cli-${{ github.sha }}

      - name: test
        run: lerna exec --scope zarm -- yarn coverage
      
      - name: coverage
        run: bash <(curl -s https://codecov.io/bash)
    needs: compile-cli

  react-17-dist:
    name: react@17.x / dist
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: restore cli
        uses: actions/cache@v2
        with:
          path: packages/zarm-cli/lib
          key: cli-${{ github.sha }}

      - name: dist
        run: lerna exec --scope zarm -- yarn build:umd
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: check
        run: lerna exec --scope zarm -- node ./tests/dekko/dist.test.js

      - name: bundlesize
        run: lerna exec --scope zarm -- yarn bundlesize
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
    needs: compile-cli

  react-16:
    name: react@16.x
    runs-on: ubuntu-latest
    env:
      REACT: 16
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: restore cli
        uses: actions/cache@v2
        with:
          path: packages/zarm-cli/lib
          key: cli-${{ github.sha }}

      - name: install react 16
        run: lerna exec --scope zarm -- yarn install-react-16

      - name: test
        run: lerna exec --scope zarm -- yarn test
    needs: [setup-react-16, compile-cli]

  react-16-dist:
    name: react@16.x / dist
    runs-on: ubuntu-latest
    env:
      REACT: 16
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: restore cli
        uses: actions/cache@v2
        with:
          path: packages/zarm-cli/lib
          key: cli-${{ github.sha }}

      - name: install react 16
        run: lerna exec --scope zarm -- yarn install-react-16

      - name: dist
        run: lerna exec --scope zarm -- yarn build:umd
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: check
        run: lerna exec --scope zarm -- node ./tests/dekko/dist.test.js

      - name: bundlesize
        run: lerna exec --scope zarm -- yarn bundlesize
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
    needs: [setup-react-16, compile-cli]
